// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDULj10JuzzdQ1H2lCfQHDRBzQ36qY84po',
    appId: '1:328093322585:web:acb6d7dcdbeac7d8001048',
    messagingSenderId: '328093322585',
    projectId: 'devfest2022dev',
    authDomain: 'devfest2022dev.firebaseapp.com',
    databaseURL: 'https://devfest2022dev-default-rtdb.firebaseio.com',
    storageBucket: 'devfest2022dev.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmoEQDq3qgeHDw1wotu7iFJaFFl6Kwf18',
    appId: '1:328093322585:android:7e2e865cf14b5168001048',
    messagingSenderId: '328093322585',
    projectId: 'devfest2022dev',
    databaseURL: 'https://devfest2022dev-default-rtdb.firebaseio.com',
    storageBucket: 'devfest2022dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAs1LxDKtHLfOAQeLqOIFSQ97ndpFkYc0',
    appId: '1:328093322585:ios:06b609f703367ecc001048',
    messagingSenderId: '328093322585',
    projectId: 'devfest2022dev',
    databaseURL: 'https://devfest2022dev-default-rtdb.firebaseio.com',
    storageBucket: 'devfest2022dev.appspot.com',
    iosClientId:
        '328093322585-t10mejvnoc76okdt4ip3ktbi3majssch.apps.googleusercontent.com',
    iosBundleId: 'com.devfestbolivia.devfestbolivia',
  );
}
